FROM openjdk:8-jre
MAINTAINER zhongshi <zhongshi@zhongshi.info>
ENV DOCKERIZE_VERSION v0.6.0
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
RUN echo "deb http://httpredir.debian.org/debian jessie main contrib" > /etc/apt/sources.list
RUN echo "deb http://security.debian.org/ jessie/updates main contrib" >> /etc/apt/sources.list
RUN echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections
RUN apt-get update
RUN apt-get install -y ttf-mscorefonts-installer
RUN apt-get clean
RUN apt-get autoremove -y
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir /usr/share/fonts/winFonts/
COPY simsun.ttc /usr/share/fonts/winFonts/